using Maestro.WorkspaceService.Application.DTOs;
using Maestro.WorkspaceService.Domain.Entities;
using Maestro.WorkspaceService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.IO;
using Maestro.WorkspaceService.Application.Services;

namespace Maestro.WorkspaceService.Application.Services;

public interface IProjectService
{
    Task<IEnumerable<ProjectDto>> GetAllProjectsAsync();
    Task<ProjectDto?> GetProjectByIdAsync(int id);
    Task<ProjectDto> CreateProjectAsync(CreateProjectRequest request);
    Task<bool> DeleteProjectAsync(int id);
    Task InitializeProjectAsync(int projectId, ProjectType type);
    object GetProjectFileTree(int projectId);
    Task<string?> GetFileContentAsync(int projectId, string relativePath);
    Task<bool> SaveFileContentAsync(int projectId, string relativePath, string content);
}

public class ProjectService(WorkspaceDbContext db, ILogger<ProjectService> logger) : IProjectService
{
    private readonly string _basePath = Environment.GetEnvironmentVariable("PROJECTS_STORAGE_PATH") ?? "/app/projects";

    public async Task<IEnumerable<ProjectDto>> GetAllProjectsAsync()
    {
        var projects = await db.Projects.ToListAsync();
        return projects.Select(MapToDto).ToList();
    }

    public async Task<ProjectDto?> GetProjectByIdAsync(int id)
    {
        var project = await db.Projects.FindAsync(id);
        return project != null ? MapToDto(project) : null;
    }

    public async Task<ProjectDto> CreateProjectAsync(CreateProjectRequest request)
    {
        var project = new Project
        {
            Name = request.Name,
            Description = request.Description ?? string.Empty,
            DueDate = request.DueDate ?? string.Empty,
            Type = request.Type,
            FrontendFramework = request.FrontendFramework ?? "React",
            BackendFramework = request.BackendFramework ?? "Express",
            Database = request.Database ?? "PostgreSQL",
            IsDockerEnabled = request.IsDockerEnabled,
            Status = "pending",
            KeycloakId = request.KeycloakId
        };

        db.Projects.Add(project);
        await db.SaveChangesAsync();
        return MapToDto(project);
    }

    public async Task<bool> DeleteProjectAsync(int id)
    {
        var project = await db.Projects.FindAsync(id);
        if (project == null) return false;

        db.Projects.Remove(project);
        await db.SaveChangesAsync();
        return true;
    }

    public async Task InitializeProjectAsync(int projectId, ProjectType type)
    {
        logger.LogInformation("[Init] Démarrage de l'initialisation pour le projet {ProjectId} ({Type})", projectId, type);

        var rootPath = Path.Combine(_basePath, projectId.ToString());
        
        try 
        {
            if (!Directory.Exists(rootPath)) Directory.CreateDirectory(rootPath);

            switch (type)
            {
                case ProjectType.Frontend:
                    await CreateFrontendTemplate(rootPath);
                    break;
                case ProjectType.Backend:
                    await CreateBackendTemplate(rootPath);
                    break;
                case ProjectType.Fullstack:
                    Directory.CreateDirectory(Path.Combine(rootPath, "frontend"));
                    Directory.CreateDirectory(Path.Combine(rootPath, "backend"));
                    await CreateFrontendTemplate(Path.Combine(rootPath, "frontend"));
                    await CreateBackendTemplate(Path.Combine(rootPath, "backend"));
                    break;
            }
            
            // Initialisation Git simulée (création du dossier .git)
            Directory.CreateDirectory(Path.Combine(rootPath, ".git"));
            await File.WriteAllTextAsync(Path.Combine(rootPath, "README.md"), $"# Project {projectId}\nGenerated by Maestro.");

            // 2. Preuve en Base de données : Changement du statut
            var project = await db.Projects.FindAsync(projectId);
            if (project != null)
            {
                project.Status = "active";
                await db.SaveChangesAsync();
                logger.LogInformation("[Init] Statut du projet {ProjectId} mis à jour en 'active'.", projectId);
            }

            logger.LogInformation("[Init] Projet {ProjectId} prêt pour l'édition.", projectId);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "[Init] Échec de l'initialisation physique pour le projet {ProjectId}", projectId);
            throw;
        }
    }

    private async Task CreateFrontendTemplate(string path)
    {
        Directory.CreateDirectory(Path.Combine(path, "src"));
        Directory.CreateDirectory(Path.Combine(path, "public"));
        await File.WriteAllTextAsync(Path.Combine(path, "package.json"), "{ \"name\": \"frontend\", \"version\": \"1.0.0\" }");
        await File.WriteAllTextAsync(Path.Combine(path, "src/App.jsx"), "export default function App() { return <h1>Maestro</h1> }");
    }

    private async Task CreateBackendTemplate(string path)
    {
        Directory.CreateDirectory(Path.Combine(path, "controllers"));
        Directory.CreateDirectory(Path.Combine(path, "models"));
        await File.WriteAllTextAsync(Path.Combine(path, "index.js"), "const express = require('express');");
    }

    public object GetProjectFileTree(int projectId)
    {
        var rootPath = Path.Combine(_basePath, projectId.ToString());
        if (!Directory.Exists(rootPath)) return new { error = "Project not found on disk" };

        return ScanDirectory(rootPath);
    }

    private object ScanDirectory(string path)
    {
        var info = new DirectoryInfo(path);
        return new
        {
            name = info.Name,
            type = "directory",
            children = info.GetFileSystemInfos()
                .Where(f => f.Name != ".git") // On cache le dossier git
                .Select(f => f is DirectoryInfo d 
                    ? ScanDirectory(d.FullName) 
                    : (object)new { name = f.Name, type = "file" })
        };
    }

    public async Task<string?> GetFileContentAsync(int projectId, string relativePath)
    {
         if (string.IsNullOrWhiteSpace(relativePath)) return null;

        // Normalisation du chemin : remplace les backslashes et retire le slash de début
        var normalizedPath = relativePath.Replace('\\', '/').TrimStart('/');
        
        var rootPath = Path.GetFullPath(Path.Combine(_basePath, projectId.ToString())) + Path.DirectorySeparatorChar;
        var fullPath = Path.GetFullPath(Path.Combine(rootPath, normalizedPath));

        logger.LogInformation("[Files] Lecture demandée - Projet: {ProjectId}, Path: {Path}", projectId, normalizedPath);

        if (!fullPath.StartsWith(rootPath, StringComparison.OrdinalIgnoreCase))
        {
            logger.LogWarning("[Security] Tentative d'accès hors du projet {ProjectId}: {FullPath}", projectId, fullPath);
            return null;

        }

        if (!File.Exists(fullPath)) 
        {
            logger.LogWarning("[Files] Fichier non trouvé sur le disque : {FullPath}", fullPath);
            return null;
        }

        return await File.ReadAllTextAsync(fullPath);
    }

    public async Task<bool> SaveFileContentAsync(int projectId, string relativePath, string content)
    {
        if (string.IsNullOrWhiteSpace(relativePath)) return false;

        var normalizedPath = relativePath.Replace('\\', '/').TrimStart('/');
        var rootPath = Path.GetFullPath(Path.Combine(_basePath, projectId.ToString())) + Path.DirectorySeparatorChar;
        var fullPath = Path.GetFullPath(Path.Combine(rootPath, normalizedPath));

        if (!fullPath.StartsWith(rootPath, StringComparison.OrdinalIgnoreCase))
        {
            logger.LogWarning("[Security] Tentative d'écriture hors du projet {ProjectId}: {FullPath}", projectId, fullPath);
            return false;
        }

        var directory = Path.GetDirectoryName(fullPath);
        if (directory != null && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        await File.WriteAllTextAsync(fullPath, content);
        logger.LogInformation("[Files] Fichier sauvegardé avec succès : {FullPath}", fullPath);
        return true;
    }

    private static ProjectDto MapToDto(Project p) => new(
        p.Id, p.Name, p.Description, p.DueDate, p.Status, 
        p.Type, p.FrontendFramework, p.BackendFramework, 
        p.Database, p.IsDockerEnabled, p.KeycloakId
    );
}
